 
create view v_month as SELECT 1 AS MONTH
    UNION SELECT 2 AS MONTH
    UNION SELECT 3 AS MONTH
    UNION SELECT 4 AS MONTH
    UNION SELECT 5 AS MONTH
    UNION SELECT 6 AS MONTH
    UNION SELECT 7 AS MONTH
    UNION SELECT 8 AS MONTH
    UNION SELECT 9 AS MONTH
    UNION SELECT 10 AS MONTH
    UNION SELECT 11 AS MONTH
    UNION SELECT 12 AS MONTH